### ISSUE TITLE
Filter streams that are NOT in the 'Science and Technology' Twitch Category

### ISSUE THREAD

**Issue by TechDufus** [powershelllive/TwitchStreamNotifcations#24]
It would be a nice feature to check the twitch category before posting tweets and discord messages.

If I want to stream a video game using my twitch account that is setup in this PowerShell Live automation, my gaming stream would still ping the PowerShell world.

It would be nice to only post the PowerShell stream when it is in specific twitch categories.

**Comment by SimonWahlin** [comment]
Sounds like a good idea!

Would like to have it configured using AppSettings.

Want to give it a try?

**Comment by TechDufus** [comment]
It looks like we may be able to look at the [TwitchWebhookIngestion.cs](https://github.com/powershelllive/TwitchStreamNotifcations/blob/master/src/functions/TwitchWebhookIngestion.cs) and filter out the stream type. Without seeing any logs, I'm not sure if this lives in the `{item.Type}` value or where else we may be able to get that info.

https://github.com/powershelllive/TwitchStreamNotifcations/blob/76b82620aaa886866a06fe623d17f85e3fccacf9/src/functions/TwitchWebhookIngestion.cs#L118-L130

**Comment by markekraus** [comment]
Wanted to provide some historical context on this ask. I don't have any particular opinion on this, but since it was discussed early in the creation of PowerShellLive, it's good to have some context before making a decision on what to do:

This was discussed in the community when we first launched. The majority at the time felt that it should not be limited to just coding streams. The idea being, this should help PSL streamers to build their communities regardless of gaming or coding.

Some ideas discussed:

* Create a way for PSL streamers to opt-out of having their gaming streams announced if they so wanted (like updating their conf in `/config/Subscriptions.json`)
* Filter any streams not in science and technology
* Filter any stream that doesn't have PowerShell in the description
* Don't filter anything

**Comment by SimonWahlin** [comment]
Thank you @markekraus for providing some context!

I see your point and I don't think there are enough notifications for this to be a problem of spamming the community. I really like the idea of letting streamers choosing when to create a notification, question is how to best do that?

We could have options like:
```
 {
      "twitchname": "<name>",
      "twittername": "<name>",
      "discordname": "<name>",
      "onlyAnnounceTags" : [
            "Programming"
      ],
      onlyAnnounceGames: [
            "science and technology"
      ]
}
```

I'm a bit worried to make it too complex, but if we get the process documented it should be OK I think.

What do you think?

**Comment by TechDufus** [comment]
@SimonWahlin
I like this approach as well.

**Comment by SimonWahlin** [comment]
Waaay later, but we now have support for optional filtering on Title and on Category per streamer.

Add any of the properties "titlefilters" or "categoryfilters" as an array of strings to "your" configuration object and we will only announce streams where the title and/or category matches any of the values provided.

Example: This should only announce streams with powershell i title.
```json
{
      "twitchname": "SimonWse",
      "twittername": "SimonWahlin",
      "discordname": "337663594957373455",
      "titlefilters": ["powershell"]
}
```
